"""baseline schema

Captures the schema produced by Base.metadata.create_all() at the time
this migration was introduced, including the columns previously created
via the _INLINE_ALTERS list in akashic.database. Existing deployments
created before Alembic was wired up should be marked at this revision
via `alembic stamp head` on first startup.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scan_schedule', sa.String(), nullable=True),
    sa.Column('exclude_patterns', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('security_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('request_ip', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_source_id'), 'audit_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('parent_path', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('acl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xattrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fs_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fs_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fs_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'path', name='uq_entries_source_path')
    )
    op.create_index('ix_entries_browse', 'entries', ['source_id', 'parent_path', 'kind'], unique=False)
    op.create_index('ix_entries_content_hash', 'entries', ['content_hash'], unique=False)
    op.create_table('fs_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_persons_user_id'), 'fs_persons', ['user_id'], unique=False)
    op.create_table('principal_groups_cache',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'identity_type', 'identifier', name='pk_principal_groups_cache')
    )
    op.create_table('principals_cache',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'sid', name='pk_principals_cache')
    )
    op.create_table('purge_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purge_type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('records_removed', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('files_found', sa.Integer(), nullable=False),
    sa.Column('files_new', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('bytes_scanned', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('current_path', sa.String(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bytes_scanned_so_far', sa.BigInteger(), nullable=True),
    sa.Column('files_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dirs_walked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dirs_queued', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_estimated', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('previous_scan_files', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'source_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('old_source_id', sa.UUID(), nullable=True),
    sa.Column('old_path', sa.String(), nullable=True),
    sa.Column('new_source_id', sa.UUID(), nullable=True),
    sa.Column('new_path', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['new_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['old_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_tags',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('tagged_by', sa.UUID(), nullable=True),
    sa.Column('tagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['tagged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_table('entry_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('acl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xattrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fs_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fs_person_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('groups_source', sa.String(), nullable=False),
    sa.Column('groups_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fs_person_id'], ['fs_persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fs_person_id', 'source_id', name='uq_fs_bindings_person_source')
    )
    op.create_index(op.f('ix_fs_bindings_fs_person_id'), 'fs_bindings', ['fs_person_id'], unique=False)
    op.create_index(op.f('ix_fs_bindings_source_id'), 'fs_bindings', ['source_id'], unique=False)
    op.create_table('scan_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_log_entries_scan_ts', 'scan_log_entries', ['scan_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_log_entries_scan_ts', table_name='scan_log_entries')
    op.drop_table('scan_log_entries')
    op.drop_index(op.f('ix_fs_bindings_source_id'), table_name='fs_bindings')
    op.drop_index(op.f('ix_fs_bindings_fs_person_id'), table_name='fs_bindings')
    op.drop_table('fs_bindings')
    op.drop_table('entry_versions')
    op.drop_table('entry_tags')
    op.drop_table('entry_events')
    op.drop_table('webhooks')
    op.drop_table('tags')
    op.drop_table('source_permissions')
    op.drop_table('scans')
    op.drop_table('purge_log')
    op.drop_table('principals_cache')
    op.drop_table('principal_groups_cache')
    op.drop_index(op.f('ix_fs_persons_user_id'), table_name='fs_persons')
    op.drop_table('fs_persons')
    op.drop_index('ix_entries_content_hash', table_name='entries')
    op.drop_index('ix_entries_browse', table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_source_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
