"""scan_snapshots

Adds the time-series snapshot table that powers storage-growth,
capacity-forecast, and file-type-trend charts. One row per
(source, scan-completion or nightly-fallback). See
api/akashic/models/scan_snapshot.py for column rationale.

Revision ID: 0002_scan_snapshots
Revises: 0001_baseline
Create Date: 2026-04-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_scan_snapshots'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('directory_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('by_extension', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('by_owner', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('by_kind_and_age', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_snapshots_source_taken', 'scan_snapshots', ['source_id', 'taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_snapshots_source_taken', table_name='scan_snapshots')
    op.drop_table('scan_snapshots')
    # ### end Alembic commands ###
