"""fs_unbound_identities

Adds the table that records OIDC identity claims that didn't match any
source's principal_domain at login. Surfaced in Settings → Identities so
admins can see "user X has SID claim Y but no source uses that domain."

Revision ID: 0003_fs_unbound_identities
Revises: 0002_scan_snapshots
Create Date: 2026-05-01
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_fs_unbound_identities'
down_revision: Union[str, None] = '0002_scan_snapshots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_unbound_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'identity_type', 'identifier', name='uq_fs_unbound_user_identity')
    )
    op.create_index(op.f('ix_fs_unbound_identities_user_id'), 'fs_unbound_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_unbound_identities_user_id'), table_name='fs_unbound_identities')
    op.drop_table('fs_unbound_identities')
    # ### end Alembic commands ###
